### ISSUE TITLE
Kanban Set Up

### ISSUE THREAD

**Issue by TimmyChan99** [TimmyChan99/Kanban-practice#21]
- [Link to project: ](https://github.com/TimmyChan99/Kanban-practice/projects/1)

- The team consists of 2 pepole.

**Comment by elyor-doniyorov** [comment]
Hi @TimmyChan99 and @netman5, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Make sure all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/67087664/151806345-2a71a53d-d4ce-4a26-b166-0c8c9831f50a.png">

- [x] All cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TimmyChan99** [comment]
Recommended changes are applied, please check the project.

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
