### ISSUE TITLE
Morning session: Peer-to-peer code review 2022-02-04

### ISSUE THREAD

**Issue by OybekKayumov** [TimmyChan99/Kanban-practice#34]
Hi Team !
👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far. 🚀
Keep on coding, good job so far! 👏

There are some issues that you still need to work on to go to the next project but you are almost there!

- [x] We suggest you publish your project according to the requirements of the project.
- [x] We think it would be better if you add a valid screenshot to your README and it would look more professional.
- [x] We think it would make the code cleaner if you remove the comments in your code base.

- [OPTIONAL] Everything is looks well but  please kindly remove blink line unless separating large code blocks  👍

**Comment by TimmyChan99** [comment]
Thanks for the feedback, I'll make sure to fix the issues ✔️
